### ISSUE TITLE
Inquiry about Code and Dataset

### ISSUE THREAD

**Issue by Little0213** [aiunibs/planGPT#1]
Hi!

I would like to thank you for your outstanding work on this project. It has been incredibly useful and inspiring.

I have a few questions regarding the training process of the GPT-2 model. Could you please provide some details on how you trained the model? Any insights or documentation would be greatly appreciated.

Additionally, I noticed that the validation set for the "zenotravel" dataset does not seem to be provided. Could you please clarify if it is available or if there are any specific instructions on how to obtain it?

Thank you for your time and assistance.

**Comment by MassimilianoT** [comment]
Hi, we are glad that you liked our work and we thank you for the kind words.
In this repository, we decided only to provide models and testing environment.
You can find some details in the ICAPS paper [(link)](https://ojs.aaai.org/index.php/ICAPS/article/download/31510/33670). 
If you have further questions please contact us at massimiliano.tummolo@unibs.it and alfonso.gerevini@unibs.it.

Regarding 'zenotravel' the issue will be solved shortly.

If you encounter other problems please reach us again.

Thank you
Best regards

**Comment by Little0213** [comment]
Hi,
Sorry for my delayed response.I would like to inquire about the progress of the "zenotravel" dataset. Has the data processing been completed? 
Thanks again for your work, and I look forward to your reply.
Best regards
